"""


Defines the final response returned by the AI Engine
to the frontend.
"""

from typing import List

from pydantic import BaseModel, Field

from .agent_schema import AgentOutput, RiskLevel


class AIResponse(BaseModel):
    """
    Final response generated by the AI Engine.
    """

    borrower_id: str = Field(
        ...,
        description="Borrower identifier"
    )

    loan_id: str = Field(
        ...,
        description="Loan identifier"
    )

    overall_risk: RiskLevel = Field(
        ...,
        description="Final aggregated risk level"
    )

    default_probability: float = Field(
        ...,
        ge=0,
        le=1,
        description="Predicted probability of default"
    )

    executive_summary: str = Field(
        ...,
        description="High-level summary for the loan officer"
    )

    key_risk_factors: List[str] = Field(
        default_factory=list,
        description="Top contributors to the final risk"
    )

    recommendations: List[str] = Field(
        default_factory=list,
        description="Recommended actions for the bank"
    )

    participating_agents: List[str] = Field(
        default_factory=list,
        description="Agents involved in producing the assessment"
    )

    agent_outputs: List[AgentOutput] = Field(
        default_factory=list,
        description="Individual outputs from each AI agent"
    )

    confidence: float = Field(
        ...,
        ge=0,
        le=1,
        description="Overall confidence of the AI Engine"
    )

    generated_by: str = Field(
        default="Risk360 AI Engine v1.0",
        description="AI Engine version"
    )